# Using -isystem instead of -I to prevent warnings for the following headers
INCLUDES += -isystem$(PKGDIRBASE)/relic/include
INCLUDES += -isystem$(BINDIR)/pkg-build/relic/include
ARCHIVES += $(BINDIR)/relic.a

ifneq (,$(filter psa_relic, $(USEMODULE)))
  DIRS += $(RIOTPKG)/relic/psa_relic
  INCLUDES += -I$(RIOTBASE)/sys/psa_crypto/include
endif
