PKG_NAME=zboss
PKG_URL=https://github.com/Lukas-Luger/zboss.git
PKG_VERSION=b8c2e2a67f900b701ef2ace345cbc355cefcb11a
PKG_LICENSE=GPL-2

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)
