include ../Makefile.sys_common

USEMODULE += ztimer
USEMODULE += ztimer_usec
USEMODULE += hashes
USEMODULE += random
USEMODULE += prng_sha256prng
USEPKG += c25519

include $(RIOTBASE)/Makefile.include