USEMODULE += tinydtls

USEMODULE += memarray
USEMODULE += psa_crypto
USEMODULE += psa_mac
USEMODULE += psa_mac_hmac_sha_256
# Cryptocell multipart hmac not implemented
USEMODULE += psa_mac_hmac_sha_256_custom_backend
USEMODULE += psa_mac_hmac_sha_256_backend_generic
USEMODULE += psa_hash
USEMODULE += psa_hash_sha_256
USEMODULE += psa_asymmetric
USEMODULE += psa_asymmetric_ecc_p256r1
# Cryptocell does not support ECC Key derivation
USEMODULE += psa_asymmetric_ecc_p256r1_custom_backend
USEMODULE += psa_asymmetric_ecc_p256r1_backend_microecc
USEMODULE += psa_aead
USEMODULE += psa_aead_aes_128_ccm
USEMODULE += tinydtls_aes
USEMODULE += tinydtls_ecc
USEMODULE += ztimer_msec

ifneq (,$(filter sock_dtls,$(USEMODULE)))
  USEMODULE += tinydtls_sock_dtls
  USEMODULE += ztimer_usec
endif
